### ISSUE TITLE
Error directory is not created

### ISSUE THREAD

**Issue by citricut** [mattwilson1024/google-photos-exif#13]
Very dumb issue. If the error directory doesn't exist the application will finish as soon as there's an error. Workaround is to just use a directory that exists :)

Awesome tool by the way, sadly I didn't find it before importing my takeout to Apple Photos and now my photo library is pretty crippled, with thousands of pictures with date today.

**Comment by mattwilson1024** [comment]
Thanks for reporting this @citricut. I've pushed a fix, so now it'll do the same check for --errorDir as it does for --outputDir. If the directory doesn't exist it'll create it automatically, if it does exist then it'll proceed if it's empty or throw an error if the directory is not empty (to avoid accidentally writing into any folders that have files in already)
