### ISSUE TITLE
Underscore in filename

### ISSUE THREAD

**Issue by NathanHazout** [mattwilson1024/google-photos-exif#17]
I tried my first batch of 500 photos.
I noticed 3 of them had the wrong timestamp (today).  
Investigating further, I see something different about those pictures:

![Screen Shot 2021-05-18 at 9 27 40](https://user-images.githubusercontent.com/329834/118602408-505d6f00-b7bb-11eb-89c0-b5345270533f.png)

Notice the underscore at the end of the filename? The json doesn't have it.  
Google's fault for sure, but maybe we can do something about it?

**Comment by ondrejsevcik** [comment]
I have similar problem in my export, but this time the filename has extra `_n` in it but json doesn't.

<img width="422" alt="image" src="https://user-images.githubusercontent.com/4136929/127780535-e1b4ceaf-95ac-4111-b7b1-169fe9744155.png">

**Comment by ondrejsevcik** [comment]
Another weird case. Seems that some files end with dash `-`. 

<img width="401" alt="image" src="https://user-images.githubusercontent.com/4136929/127781382-c6d6c85d-9b16-4d5f-b9cb-e8d2e3a81ce8.png">
