### ISSUE TITLE
Support .HEIC and .MOV (HEVC encoded) files

### ISSUE THREAD

**Issue by inakaboy** [mattwilson1024/google-photos-exif#22]
Currently, files with extension .HEIC, .MOV, and .mov are ignored and not included in the output. Such files are commonly generated by Apple devices such as iPhones.

**Comment by mattwilson1024** [comment]
Thanks for the suggestion @inakaboy. I've pushed an update which adds support for HEIC and MOV file extensions out of the box, and also adds a `config.ts` file which allows the list of supported extensions to be easily customised.

**Comment by inakaboy** [comment]
Great, thanks, amazingly quick! Actually I forgot to mention that yesterday I started working on a fork to add more file types, but your solution is more elegant than mine anyway. Thanks very much!
