### ISSUE TITLE
Unexpected Argument Error - Am I using file paths correctly?

### ISSUE THREAD

**Issue by mpuricelli** [mattwilson1024/google-photos-exif#45]
Hi,

Thank you for building this tool and sharing it with us all.

I'm running into an issue when trying to run this tool.

I get an "unexpected arguments" error when running the **yarn start** command.

Am I using the file paths correctly?

Thanks,

Marc

<img width="997" alt="Screenshot 2024-08-10 at 11 08 57" src="https://github.com/user-attachments/assets/1726c77b-2e5f-479e-8bfd-afd5953a0bef">

**Comment by mattwilson1024** [comment]
You've not got the syntax quite right there. Create the `Output` and `Errors` directories first (I can't remember if the tool creates them for you automatically or not), then try: 

```
yarn start --inputDir /Users/marcpuricelli/google-photos-exif/Takeout --outputDir /Users/marcpuricelli/google-photos-exif/Output --errorDir /Users/marcpuricelli/google-photos-exif/Errors
```

**Comment by mpuricelli** [comment]
It works.

Thank you so much Matt!
